name: App build
on:
  push:
jobs:
  build_with_signing:
    runs-on: macos-14
    environment: IOS_ANDROID_PUBLISH_V1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: decrypt archive
        env:
          SYMMETRIC_KEYFILE_BASE64: ${{ secrets.SYMMETRIC_KEYFILE_BASE64 }}
        run: |
          echo -n "$SYMMETRIC_KEYFILE_BASE64" | base64 --decode -o "$GITHUB_WORKSPACE/symmetric_keyfile.key"
          ls "$GITHUB_WORKSPACE"
          chmod +x $GITHUB_WORKSPACE/decompress.sh
          $GITHUB_WORKSPACE/decompress.sh

      - name: List files in the repository
        run: |
          ls $GITHUB_WORKSPACE/PuntoEttoreExtraFiles
          rm -rf $GITHUB_WORKSPACE/PuntoEttoreExtraFiles
